### PR TITLE
Allow Hyper 0.10

### PR DESCRIPTION
**Pull request by untitaker**

### CODE REVIEW

**Comment by SimonSapin** [comment]
Looks good. Assuming that you’ll also want this on crates.io, please also increment the version number. Thanks!

**Comment by SimonSapin** [comment]
I think this is not a breaking change, so 0.4.1.

**Comment by untitaker** [comment]
Ok I've bumped the version. However, I think you still need to set the git tag.

**Comment by SimonSapin** [comment]
Tagged and published :)

**Pull request merged**
