### PR TITLE
Move tests into separate folder

### PR DESCRIPTION
**Pull request by Ygg01**
Separate into special test folder.

### CODE REVIEW

**Comment by SimonSapin** [comment]
Why?

**Comment by Ygg01** [comment]
More idiomatic? Plus keeping them separate also somewhat serves as a more realistic example.

**Comment by Ygg01** [comment]
I think this is pretty much dead. Closing.

**Comment by SimonSapin** [comment]
Sorry I forgot to respond. Yeah, it doesn’t seem that much more idiomatic to me, and maybe slightly less convenient.

**Pull request closed without merging**
