### PR TITLE
Add example of Kuchiki parsing a page

### PR DESCRIPTION
**Pull request by Ygg01**
This is a small stand-alone example that describes how to get
a page, parse it and print one content of a node (in this case a Mozilla Easter
egg).

I've ran into a small issue (see #13 ). Also it might be prudent to wire up tests so that even examples are tested, to prevent code rot.

### CODE REVIEW

**Comment by SimonSapin** [comment]
Rather than a separate Cargo package, please make this a single `examples/hyper.rs` file. `cargo test` at the repository top-level will build it automatically (but not run it). Hyper can be in `[dev-dependencies]` to make this work.

**Comment by Ygg01** [comment]
I see, my reasoning was that a separate Cargo package would be a better demo of potential usage than a script. I'll get on it.

**Comment by Ygg01** [comment]
Well, I meant this more as a nice demo, than as anything substantial. 

So, I'm (sadly) not the customer kuchiki is looking for. I just hope someone uses it.

**Comment by SimonSapin** [comment]
Wait, what? How does using Cargo’s built-in support for examples rather than a separate example crate mean that Kuchiki is not for you?

**Comment by Ygg01** [comment]
Sorry, I should have been more clear. I meant as separate points. Point one, tried to test examples manually, was tedious. 

Point two, I don't have a project that requires extensive reading/parsing HTML :(  and thus I'm not really Kuchiki's target audience. It's a superb project, I like contributing, but it just doesn't fit into my current projects. 

Maybe in future I'll have something that requires kuchiki. Just not at the moment.

**Comment by SimonSapin** [comment]
Thanks!

**Pull request merged**
