### PR TITLE
Switch to 2018 edition

### PR DESCRIPTION
**Pull request by mashedcode**
Basically upgrade dependencies and `cargo fix`.

Poorly cssparser can't be upgraded yet as we're waiting for a selectors crate release.

### CODE REVIEW

**Comment by SimonSapin** [comment]
Are you aware that you don’t need every crate in your program to be on the same edition? And that future compiler versions will always support older editions? You can start using Rust 2018 in your own code without you whole dependency graph doing so. That’s the whole point of having this "edition" mechanism, rather than an incompatible Rust 2.x version.

**Comment by mashedcode** [comment]
@SimonSapin the reason why I included the upgrade to the 2018 edition in this PR is because otherwise it wouldn't compile due to dependent crates that use 2018 edition features.

To be clear I really just need the upgrade to html5ever 0.25 to avoid clashes with other crates that depend on the up-to-date version.

**Comment by SimonSapin** [comment]
> To be clear I really just need the upgrade to html5ever 0.25 to avoid clashes with other crates that depend on the up-to-date version.

Ah, fair enough. That should have been the title of the PR, though!

**Comment by mashedcode** [comment]
@SimonSapin the switch to 2018 edition is the "major" change. Yes, I could've called it "Upgrade dependencies".

**Comment by mashedcode** [comment]
Any feedback? Please close the PR if it's not considered for merging.

**Comment by jens1o** [comment]
I'd also be keen whether this is something that wants to be resolved (i.e. switching to the current edition), or not.

**Comment by Ygg01** [comment]
@mashedcode @jens1o does jdm PR #65  already has what you peeps need?

**Comment by mashedcode** [comment]
Closing in favor of #65 which will hopefully be merged after review.

**Pull request closed without merging**
