### PR TITLE
Add ability to specify traversal scope for node serialize

### PR DESCRIPTION
**Pull request by max-frai**
Sometimes we need in something like `innerHTML` in javascript. This pull request adds ability to specify serialize scope and we can get content of node children as html.

### CODE REVIEW

**Comment by SimonSapin** [comment]
If we’re adding configurability, let’s instead add a method that takes a whole `SerializeOpts`. Could you change this PR to do that? Thanks.

**Comment by max-frai** [comment]
Sorry, I tried to push examples as new pull request but something went wrong and now all commits are together :(

**Comment by max-frai** [comment]
Sorry for disturbing. Any chance this will be merged and published?
If there are any problems I will solve them. Thank you.

**Comment by seijikun** [comment]
Maybe a shortcut for the innerHTML functionality (`-> String`) would be nice as well?
Something like:

```rust
impl NodeRef {
    [...]

    /// Get the inner HTML code.
    #[inline]
    pub fn inner_html(&self) -> Result<String> {
        let mut u8_vec = Vec::new();
        serialize(&mut u8_vec, self, SerializeOpts {
            traversal_scope: ChildrenOnly(None),
            ..Default::default()
        })?;
        String::from_utf8(u8_vec).map_err(|err| io::Error::new(io::ErrorKind::InvalidData, err))
    }
}
```

**Comment by Ygg01** [comment]
@max-frai this might require some rebase, there seem to be some conflicts.

**Comment by SimonSapin** [comment]
I will soon archive this repository and make it read-only, so this PR will not be addressed: https://github.com/kuchiki-rs/kuchiki#archived

**Pull request closed without merging**
